<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-REH8PLD" ignored="0" tests="5" failures="1" timestamp="2024-01-30T13:30:56 MSK" time="0.2" errors="0">
  <testcase name="getData_failConnect" time="0.06" classname="FtpClientTest">
    <failure type="org.testng.TestException" message="
Method FtpClientTest.getData_failConnect()[pri:0, instance:FtpClientTest@77b52d12] should have thrown an exception of type class java.net.ConnectException">
      <![CDATA[org.testng.TestException: 
Method FtpClientTest.getData_failConnect()[pri:0, instance:FtpClientTest@77b52d12] should have thrown an exception of type class java.net.ConnectException
at java.util.ArrayList.forEach(ArrayList.java:1249)
at RunTest.main(RunTest.java:14)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- getData_failConnect -->
  <testcase name="getData_failIP" time="0.04" classname="FtpClientTest"/>
  <testcase name="getData_failLogin" time="0.0" classname="FtpClientTest"/>
  <testcase name="getData_failPass" time="0.04" classname="FtpClientTest"/>
  <testcase name="getData_success" time="0.05" classname="FtpClientTest"/>
</testsuite>
